#!/usr/bin/python

from sensorReaderMaxbotix import read_distance
import sys
import time
import gspread
import serial
from datetime import datetime
from oauth2client.service_account import ServiceAccountCredentials

def execute_process(numberOfSensor):

      while True:
        date = datetime.now().strftime("%m/%d/%Y")
        timeNow = datetime.now().strftime("%I:%M %p")
        for sensorIndex in range(0, int(numberOfSensor)):
          distance = read_distance("/dev/ttyUSB" + str(sensorIndex))
          print "Sensor:" + str(sensorIndex) + "| Distance: " + str(distance)

        time.sleep(1)

if __name__ == "__main__":
    if len(sys.argv) > 0:
        execute_process(str(sys.argv[1]))
    else:
        print "Please pass the number of sensor(s) attached to the device."
