#!/usr/bin/python

from checknetwork import internet_on
from sensorReaderMaxbotix import read_distance
from googleuploader import upload_row_to_google_sheet, upload_realtime_reading_to_google_sheet
import sys
import time
import gspread
import serial
from datetime import datetime
from oauth2client.service_account import ServiceAccountCredentials

def write_to_file(date, timeNow, distance):
    file = open('readingCollectionDB', 'a')
    file.write(str(date) + "," + str(timeNow) + "," + str(distance) + "\n")
    print("Wrote to file: Date:" + str(date) + " | Time:" + str(timeNow) + " | Distance:" + str(distance))
    file.close()

def execute_process(key, numberOfSensor):

      while True:
        date = datetime.now().strftime("%m/%d/%Y")
        timeNow = datetime.now().strftime("%I:%M %p")
        for sensorIndex in range(0, int(numberOfSensor)):
          distance = read_distance("/dev/ttyUSB" + str(sensorIndex))
          print "Sensor:" + str(sensorIndex) + "| Distance: " + str(distance)

        time.sleep(1)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        execute_process(str(sys.argv[1]), str(sys.argv[2]))
    else:
        print "Please pass the key of the spreadsheet as the paramter"
